#!/usr/bin/env python3
"""Generate WeeklyTop50.md from GitHub's most-starred public repositories."""

from __future__ import annotations

import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover - Python 3.8 fallback.
    ZoneInfo = None


GITHUB_SEARCH_URL = "https://api.github.com/search/repositories"
OUTPUT_PATH = Path("WeeklyTop50.md")
TOP_N = 100


def get_scan_date() -> str:
    timezone_name = os.environ.get("SCAN_TIMEZONE", "America/Chicago")
    if ZoneInfo is None:
        now = dt.datetime.now(dt.timezone.utc)
    else:
        now = dt.datetime.now(ZoneInfo(timezone_name))
    return now.date().isoformat()


def fetch_top_repositories() -> list[dict]:
    query = {
        "q": "stars:>1 fork:false archived:false",
        "sort": "stars",
        "order": "desc",
        "per_page": str(TOP_N),
    }
    url = f"{GITHUB_SEARCH_URL}?{urllib.parse.urlencode(query)}"
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "best-of-github-weekly-top50",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        body = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API request failed: {error.code} {body}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"GitHub API request failed: {error.reason}") from error

    repositories = payload.get("items", [])
    if len(repositories) < TOP_N:
        raise RuntimeError(f"Expected {TOP_N} repositories, got {len(repositories)}")
    return repositories[:TOP_N]


def markdown_escape(value: str | None) -> str:
    if not value:
        return "-"
    return (
        value.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("\r", " ")
        .replace("\n", " ")
        .strip()
    )


def render_markdown(repositories: list[dict]) -> str:
    lines = [
        "# Weekly Top 100 GitHub Repositories",
        "",
        f"Scanned on {get_scan_date()}.",
        "",
        "This weekly report lists the top 100 public, non-fork, non-archived GitHub repositories sorted by star count. The list is generated from the GitHub Search API.",
        "",
        "| Rank | Repository | Stars | Language | Description |",
        "| ---: | --- | ---: | --- | --- |",
    ]

    for rank, repository in enumerate(repositories, start=1):
        full_name = repository["full_name"]
        html_url = repository["html_url"]
        stars = f"{repository['stargazers_count']:,}"
        language = markdown_escape(repository.get("language"))
        description = markdown_escape(repository.get("description"))
        lines.append(
            f"| {rank} | [{full_name}]({html_url}) | {stars} | {language} | {description} |"
        )

    lines.extend(
        [
            "",
            "<!-- This file is generated by scripts/update_weekly_top50.py. -->",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    repositories = fetch_top_repositories()
    OUTPUT_PATH.write_text(render_markdown(repositories), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} with {len(repositories)} repositories.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as error:
        print(error, file=sys.stderr)
        raise SystemExit(1)
